create bases
ThiagoFiorelli/Marketplace_Dupla pull request #23
Opened 2021-01-15 13:54 UTC by reberetta

Arquivos de base criados e novo dao/controller de categorias e marketplace

2021-01-15 14:18 UTC, clara-odebrecht requested changes
Algumas sugestões

2021-01-15 14:18 UTC, clara-odebrecht commented on back_end/controller/ctrl_marketplace.py
> +from .base_controller import BaseController
Acho que aqui tu vai precisar importar da pasta toda, já que a referencia dele é a raiz.

2021-01-15 14:18 UTC, clara-odebrecht commented on back_end/dao/dao_sql_category.py
>  from back_end.dao.connection import Connection
O import de conexão pode ser retirado.

2021-01-15 14:18 UTC, clara-odebrecht commented on back_end/dao/dao_sql_category.py
> +    def create(self, model:Category) -> list:
O retorno da função é None.

2021-01-15 14:18 UTC, clara-odebrecht commented on back_end/dao/dao_sql_marketplace.py
>  from back_end.dao.connection import Connection
Aqui também, conexão pode tirar.

2021-01-15 14:21 UTC, Marcellort requested changes

2021-01-15 14:21 UTC, Marcellort commented on back_end/controller/ctrl_category.py
Essas funções a baixo não deveriam estar comentadas igual as do arquivo ctrl_marketplace?

2021-01-15 14:24 UTC, Marcellort requested changes

2021-01-15 14:24 UTC, Marcellort commented on back_end/controller/ctrl_category.py
>  def create_category(cat: Category)->None:
Esse código devia estar comentado igual a do controller ctrl_marketplace?

2021-01-15 14:25 UTC, Marcellort commented on back_end/controller/ctrl_category.py
>  def create_category(cat: Category)->None:
As def abaixo desse bloco, nãos sei porque o git não os seleciona

2021-01-15 16:14 UTC, reberetta commented on back_end/dao/dao_sql_category.py
>  from back_end.dao.connection import Connection
Arrumado

2021-01-15 16:15 UTC, reberetta commented on back_end/dao/dao_sql_category.py
> +    def create(self, model:Category) -> list:
Arrumado

2021-01-15 16:15 UTC, reberetta commented on back_end/dao/dao_sql_marketplace.py
>  from back_end.dao.connection import Connection
Arrumado

2021-01-15 16:41 UTC, reberetta commented on back_end/controller/ctrl_category.py
>  def create_category(cat: Category)->None:
Removi tudo que era comentário, estava receosa de apagar o código antigo... Mas mandei ver rs

2021-01-15 18:12 UTC, clara-odebrecht approved these changes

2021-01-15 18:17 UTC, julianaklulo commented on back_end/dao/dao_category.py
> +            category.id = result[0]
Por que o construtor da classe Category não recebe o id? Evitaria de precisar passar o id separado.

2021-01-15 18:18 UTC, julianaklulo commented on back_end/dao/dao_marketplace.py
> +        mkp.id = result[0]
Mesma coisa pro construtor da classe Marketplace.

2021-01-15 18:49 UTC, GSA18 approved these changes

2021-01-15 19:04 UTC, clara-odebrecht approved these changes

2021-01-15 19:11 UTC, julianaklulo commented on back_end/dao/dao_marketplace.py
> +        query = f"INSERT INTO marketplaces (name_mktplaces, description) values('{mkp.name}','{mkp.description}');"
Nos valores do insert, deveria ser `model.name`, `model.description`.

2021-01-15 19:14 UTC, julianaklulo commented on front_end/web.py
> +        MarketplaceController.update(identifier, mkp)
O ìdentifier` é realmente necessário, dado que `mkp` já possui o identifier?

2021-01-15 19:16 UTC, julianaklulo commented on front_end/web.py
> +        MarketplaceController.update(identifier, mkp)
Além disso, no BaseController o método `.update()`recebe apenas o modelo como parâmetro.

2021-01-15 19:20 UTC, reberetta commented on back_end/dao/dao_marketplace.py
> +        mkp.id = result[0]
arrumado em novo commit

2021-01-15 19:33 UTC, julianaklulo commented on back_end/dao/dao_marketplace.py
> +        mkp.id = result[0]
Vi o commit consertando de categoria, mas não o de marketplace

2021-01-15 20:30 UTC, reberetta commented on back_end/dao/dao_marketplace.py
> +        mkp.id = result[0]
faltou mandar mesmo, resolvido

2021-01-15 20:47 UTC, julianaklulo approved these changes

2021-01-18 14:46 UTC, Marcellort approved these changes

2021-01-18 14:48 UTC, merged