Adiciona funcionalidade de cadastro de categorias
ThiagoFiorelli/Marketplace_Dupla pull request #4
Opened 2021-01-06 20:58 UTC by julianaklulo

2021-01-06 21:07 UTC, Marcellort requested changes

2021-01-06 21:07 UTC, Marcellort commented on front_end/templates/home.html
> +     <li>
A indentação acabou saindo com um espacinho de nada

2021-01-06 21:09 UTC, ThiagoFiorelli approved these changes
Ta tudo show!

2021-01-06 21:11 UTC, Marcellort approved these changes

2021-01-07 12:15 UTC, olgaleao approved these changes
topíssimo. :+1:

2021-01-07 12:21 UTC, merged